# Generated by Django 2.1.4 on 2018-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=190, unique=True, verbose_name='名称')),
                ('price', models.PositiveIntegerField(verbose_name='単価')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
