# Generated by Django 2.1.4 on 2018-12-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='個数')),
                ('amount', models.PositiveIntegerField(verbose_name='売上')),
                ('saled_at', models.DateTimeField(verbose_name='販売日時')),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='items.Item', verbose_name='果物')),
            ],
        ),
    ]
