# Generated by Django 2.1.4 on 2018-12-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.PositiveIntegerField(default=80, verbose_name='売上'),
            preserve_default=False,
        ),
    ]
